apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: profile-app
  template:
    metadata:
      labels:
        app: profile-app
    spec:
      containers:
      - name: profile-app-container
        image: samsonidowu/profile-app-image:latest
        ports:
        - containerPort: 3000
# Resource Allocation:         
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
# configMap Connection: 
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: mongo-db-configmap
              key: MONGO_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mongo-db-configmap
              key: MONGO_PASSWORD


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-db
  template:
    metadata:
      labels:
        app: profile-db
    spec:
      containers:
      - name: mongo-db-container
        image: mongo:latest
        ports:
        - containerPort: 27017
      restartPolicy: Always
# Defining Environment Variables:
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: mongo-db-configmap
              key: MONGO_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mongo-db-configmap
              key: MONGO_PASSWORD