apiVersion: v1
kind: Pod
metadata:
  name: profile-app-pod
  labels:
    app: profile-app
spec:
  containers:
  - name: profile-app-container
    image: samsonidowu/profile-app-image:latest
    ports:
    - containerPort: 3000
