apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: profile-app
  ports:
    - name: profile-app 
      port: 3000
      targetPort: 3000
  type: NodePort
---

apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: profile-db
  ports:
    - name: profile-db
      port: 27017
      targetPort: 27017
  type: NodePort