apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: profile-app-statefulset
spec:
  serviceName: profile-app-service
  replicas: 3
  selector:
    matchLabels:
      app: profile-app
  template:
    metadata:
      labels:
        app: profile-app
    spec:
      containers:
      - name: profile-app-container
        image: samsonidowu/profile-app-image:latest
        ports:
        - containerPort: 3000
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: profile-app-secret
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: profile-app-secret
                key: password
        volumeMounts:
          - name: profile-db-pv
            mountPath: /data/profile-db-pv
      volumes:
        - name: profile-db-pv
          persistentVolumeClaim:
            claimName: profile-db-pvc

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-db-statefulset
spec:
  serviceName: mongo-db-service
  replicas: 1
  selector:
    matchLabels:
      app: profile-db
  template:
    metadata:
      labels:
        app: profile-db
    spec:
      containers:
        - name: mongo-db-container
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: profile-app-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: profile-app-secret
                  key: password
          volumeMounts:
            - name: profile-db-pv
              mountPath: /data/profile-db-pv
      volumes:
        - name: profile-db-pv
          persistentVolumeClaim:
            claimName: profile-db-pvc
